config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs

  root 'songs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  def Song.import(filename)
    content = File.read(filename)
    content.each_line do |line|
      song = Song.new
      parts = line.split("\t")
      title_parts = parts[0].split("-")
      song.artist = title_parts[0].strip
      song.title = title_parts[1]&.strip
      song.key = parts[1].to_i
      rating_size = parts[2]&.size
      song.rating = rating_size == nil ? nil : rating_size * 2
      song.priority = parts[3].to_i
      song.comment = parts[4]
      song.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order('rating DESC, priority DESC, artist ASC, title ASC').all

  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_url, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to songs_url, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :title, :key, :rating, :priority, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
# encoding: utf-8
module SongsHelper
  def rating_stars(rating)
    if !rating || rating == 0
      ''
    elsif rating < 11
      '⭐️' * (rating / 2) + '✨' * (rating % 2)
    else
      '🌟' * 5
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utabase</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

  <meta name="HandheldFriendly" content="true">
  <meta name="apple-mobile-web-app-capable" content="yes">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
Hello World

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :key %>
    <%= f.hidden_field :key %>
    <div class="buttonContainer">
      <% (-5..5).each do |key| %>
        <button type="button" class="setKey" data-key="<%=key %>"><%=key %></button>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.hidden_field :rating %>
    <div class="buttonContainer">
      <button type="button" class="setRating" data-rating="1">　</button>
      <button type="button" class="setRating" data-rating="2">⭐️</button>
      <button type="button" class="setRating" data-rating="3">　</button>
      <button type="button" class="setRating" data-rating="4">⭐️</button>
      <button type="button" class="setRating" data-rating="5">　</button>
      <button type="button" class="setRating" data-rating="6">⭐️</button>
      <button type="button" class="setRating" data-rating="7">　</button>
      <button type="button" class="setRating" data-rating="8">⭐️</button>
      <button type="button" class="setRating" data-rating="9">　</button>
      <button type="button" class="setRating" data-rating="10">⭐️</button>
      <button type="button" class="setRating" data-rating="11">　</button>
    </div>

  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.hidden_field :priority %>
      <div class="buttonContainer">
      <% [0, 1, 2, 3].each do |prio| %>
        <button type="button" class="setPrio" data-prio="<%=prio %>"><%=prio %></button>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Destroy', @song, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>歌ベース</h1>
<%= link_to 'Add Song', new_song_path %>

<% if user_signed_in? %>
  | <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% end %>


<table>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td>
          <%= song.artist %> - <%= song.title %>
          <% if song.comment.present? %>
            <br /><span style="font-size: smaller"><%= song.comment %></span>
          <% end %>
        </td>
        <td class="align-right">
          <% if song.key.present? && song.key != 0 %>
            <div class="key"><%= song.key %></div>
          <% end %>
        </td>
        <td><%= rating_stars(song.rating) %></td>
        <td>
          <% if song.priority.present? && song.priority != 0 %>
            <%= song.priority %>
          <% end %>
        </td>
        
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Key:</strong>
  <%= @song.key %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @song.rating %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @song.priority %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @song.comment %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>